"""empty message

Revision ID: 1d0c602a46f1
Revises: c799b9eaaa2f
Create Date: 2019-12-15 06:41:30.971901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0c602a46f1'
down_revision = 'c799b9eaaa2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('prim', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'prim')
    # ### end Alembic commands ###
