"""empty message

Revision ID: 1d0e9d6ecf10
Revises: 4a02fd754f57
Create Date: 2019-12-14 11:24:11.679834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0e9d6ecf10'
down_revision = '4a02fd754f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromuser', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('alreadyhave', sa.Integer(), nullable=True),
    sa.Column('latc', sa.String(length=20), nullable=False),
    sa.Column('longc', sa.String(length=20), nullable=False),
    sa.Column('files', sa.String(length=500), nullable=False),
    sa.Column('addres', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
