"""empty message

Revision ID: 7b9e926186a3
Revises: 1d0e9d6ecf10
Create Date: 2019-12-14 11:46:58.175392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9e926186a3'
down_revision = '1d0e9d6ecf10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tags')
    # ### end Alembic commands ###
