"""empty message

Revision ID: c799b9eaaa2f
Revises: 
Create Date: 2019-12-15 05:33:17.958945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c799b9eaaa2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromuser', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('alreadyhave', sa.Integer(), nullable=True),
    sa.Column('latc', sa.String(length=20), nullable=True),
    sa.Column('longc', sa.String(length=20), nullable=True),
    sa.Column('files', sa.String(length=1000), nullable=True),
    sa.Column('addres', sa.String(length=150), nullable=True),
    sa.Column('tags', sa.String(length=1000), nullable=True),
    sa.Column('article', sa.String(length=1500), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('logged', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('posts')
    # ### end Alembic commands ###
