"""empty message

Revision ID: f5092b69f2f5
Revises: 1295913cd213
Create Date: 2019-12-15 13:15:26.246912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5092b69f2f5'
down_revision = '1295913cd213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('visibility', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'visibility')
    # ### end Alembic commands ###
